version: '3.8'

services:
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    expose:
      - "5432"

volumes:
  postgres_data: